baseURL = "https://storj.io/"
languageCode = "en-us"
title = "storj.io"

[permalinks]
  404 = "/404/"
  community = "/community/"
  partners = "/partners/"
  privacy-policy = "/privacy-policy/"
  terms-of-use = "/terms-of-use/"
  terms-of-service = "/terms-of-service/"
  code-of-conduct = "/code-of-conduct/"
  information-policy = "/information-policy/"
  storage-sla = "/storage-sla/"
  canary = "/canary/"
  whitepaper = "/whitepaper/"
  team = "/team/"
  careers = "/careers/"
  press = "/press/"
  press-kit = "/press-kit/"
  open-source = "/open-source/"
  sign-up = "/sign-up/"
  storage-node-operator="/storage-node-operator/"
  sign-up-node-operator = "/sign-up-node-operator/"
  storj-share-information = "/storj-share-information/"
  community-reporting = "/community-reporting/"
  storage-node-estimator = "/storage-node-estimator/"
  storj-share-terms = "/storj-share-terms/"
  spanish-invite = "/spanish-invite/"
  german-invite = "/german-invite/"
  russian-invite = "/russian-invite/"
  mandarin-invite = "/mandarin-invite/"
  sign-up-success = "/sign-up-success/"
  thankyou = "/thankyou/"
  blog = "/blog/"
  post = "/blog/:year/:month/:title/"



  # Pagination
  paginate = 6
  paginatePath = "page"

  [outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"

  [mediaTypes]
    [mediaTypes."text/yaml"]
      suffixes = ["yml"]

  [taxonomies]
    category = "categories"
    author = "authors"

  # Google analytics
  googleAnalytics = "UA-47268287-3"

  [params]
    # Main sections (currently used for the recent posts in the sidebar)
    mainSections = ["post"]

    # Date format (default: Jan 2, 2006)
    # date_format = "Jan 2, 2006"

    # Display post summaries instead of content in list templates (default: true)
    # truncate = false

    [params.sidebar]
      # Whether to show the recent posts or not (default: true)
      # showRecent = false

      # Whether to show the taxonomies or not (default: true)
      # showTaxonomy = false

      # How many posts to show on the sidebar (Default: 5)
      # num_recent_posts = 5


    [params.sidebar2]
      # Whether to show the recent posts or not (default: true)
      # showRecent = false

      # Whether to show the taxonomies or not (default: true)
      # showTaxonomy = false

      # How many posts to show on the sidebar (Default: 5)
      # num_recent_posts = 3
