baseURL = "/"
languageCode = "en-us"
title = "Storj.io"

[permalinks]
  developers = "/developers/"
  community = "/community/"
  partners = "/partners/"
  support = "https://storjlabs.atlassian.net/servicedesk/customer/portals"
  blog = "https://storj.io/blog"
