baseURL = "/"
languageCode = "en-us"
title = "Storj.io"

[permalinks]
  developers = "/developers/"
  community = "/community/"
  partners = "/partners/"
  privacy-policy = "/privacy-policy/"
  terms-of-use = "/terms-of-use/"
  terms-of-service = "/terms-of-service/"
  code-of-conduct = "/code-of-conduct/"
  information-policy = "/information-policy/"
  storage-sla = "/storage-sla/"
  canary = "/canary/"
  whitepaper = "/whitepaper/"
  team = "/team/"
  careers = "/careers/"
  press = "/press/"
  open-source = "/open-source/"
  sign-up = "/sign-up/"
  sign-up-farmer = "/sign-up-farmer/"
  storj-share-information = "/storj-share-information/"
  community-reporting = "/community-reporting/"
