[[redirects]]
  from = "/blog/*"
  to = "https://thirsty-austin-89166b.netlify.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/clone"
  to = "https://gist.githubusercontent.com/zeebo/ecc0abd0aec09c9eff85b12d788dfc81/raw/storj-clone"
  status = 302
  force = true

[[redirects]]
  from = "/storage-node-estimator"
  to = "https://storj.io/blog/2019/01/sharing-storage-space-for-fun-and-profit/"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "deny"
    Strict-Transport-Security = "max-age=300; includeSubDomains"
