apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: {{ .Values.fqdn | replace "." "-" }}-oauth
  name: {{ .Values.fqdn | replace "." "-" }}-oauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.fqdn | replace "." "-" }}-oauth
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.fqdn | replace "." "-" }}-oauth
    spec:
      containers:
      - env:
        - name: BIND
          value: 0.0.0.0:3000
        - name: HOST
          value: {{ .Values.fqdn }}/oauth
        - name: SESSION_SECRET
          value: {{ required "Must have a session secret" .Values.oauth.session_secret }}
        - name: GITHUB_KEY
          value: {{ required "Must have a github key" .Values.oauth.github_key }}
        - name: GITHUB_SECRET
          value: {{ required "Must have a github secret" .Values.oauth.github_secret }}
        image: storjlabs/netlify-cms-oauth-provider-go:{{ .Values.oauth.image_tag }}
        imagePullPolicy: IfNotPresent
        name: netlify-cms-oauth-provider-go
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
