apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: {{ .Values.redirect.subdomain }}-{{ .Values.fqdn | replace "." "-" }}
  name: {{ .Values.redirect.subdomain }}-{{ .Values.fqdn | replace "." "-" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.redirect.subdomain }}-{{ .Values.fqdn | replace "." "-" }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.redirect.subdomain }}-{{ .Values.fqdn | replace "." "-" }}
    spec:
      containers:
      - image: storjlabs/blog-redirect:{{ .Values.docker_image_tag }}
        imagePullPolicy: Always
        name: blog-redirect
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
