apiVersion: v1
kind: Service
metadata:
  annotations:
  name: {{ .Values.fqdn | replace "." "-" }}-oauth
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{ .Values.fqdn | replace "." "-" }}-oauth
  sessionAffinity: None
  type: ClusterIP
