backend:
  name: git-gateway
  branch: master


media_folder: "static/"
public_folder: "/"

collections:
  - name : "canary"
    label: "canary"
    folder: "content/canary/"
    create: false
    slug: "{{slug}}"
    fields: 
     - {label: "Title", name: "title", widget: "string"}
     - {label: "Body", name: "body", widget: "markdown"}
  - name : "code of conduct"
    label: "code of conduct"
    folder: "content/code-of-conduct"
    create: false
    slug: "{{slug}}"
    fields: 
     - {label: "Title", name: "title", widget: "string"}
     - {label: "Body", name: "body", widget: "markdown"}
  - name : "community"
    label: "community"
    files: 
      - label : "center box"
        name : "title"
        file : "/content/community/box*.md"
        fields :      
        - {label: "Title", name: "title", widget: "hidden"}
        - {label: "heading", name : "heading", widget: "string"}
        - {label: "ctaText", name : "ctaText", widget: "string"}
        - {label: "ctaLink", name : "ctaLink", widget: "string"}
        - {label: "img", name: "img", widget: "image", required: false }
        - {label: "description", name : "description", widget: "string"}
