backend:
  name: git-gateway
  branch: master


media_folder: "static/"
public_folder: "/"

collections:
  - name : "canary"
  - label: "canary"
  - folder: "content/canary"
  - create: false
  - slug: "{{slug}}"
  - fields: 
     - {label: "Body", name: "body", widget: "markdown"}